// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"]!,
    // directUrl is not in Prisma v7 TS types but is valid at runtime for Supabase migration direct connections
    ...( process.env["DIRECT_URL"] ? { directUrl: process.env["DIRECT_URL"] } : {}),
  } as { url: string },
});
